/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class csw_jeasyx_src_CreateNative */

#ifndef _Included_csw_jeasyx_src_CreateNative
#define _Included_csw_jeasyx_src_CreateNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     csw_jeasyx_src_CreateNative
 * Method:    nativeCreateDlist
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_csw_jeasyx_src_CreateNative_nativeCreateDlist
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
