/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class csw_jeasyx_src_JDisplayListBase_FontDef */

#ifndef _Included_csw_jeasyx_src_JDisplayListBase_FontDef
#define _Included_csw_jeasyx_src_JDisplayListBase_FontDef
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
