#!/bin/bash

use glp;

load data local infile 'load_objects.dat' into table objects;

-- create index layer_id on objects(layer_id);


-- There is no load data that works for geometry data.
-- The jt.sql script is generated by a java program that
-- reads the load_objects.dat file and uses the bounding
-- box limits.  These limits are used to format a text
-- polygon which is inserted, along with the object_id,
-- into the objects_geom table.  It's a hack, but none of
-- the suggestions I tried from the internet worked.

source jt.sql;

-- create spatial index bbox on objects_geom(bbox);


-- The remaining tables use a straight forward simple load.

load data local infile 'load_id_lookup.dat' into table pline_id_lookup;

load data local infile 'load_points_lookup.dat' into table pline_points_lookup;

load data local infile 'global.dat' into table global_stuff;
