/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class csw_jsurfaceworks_src_JSurfaceWorks_FinalizedTmeshID */

#ifndef _Included_csw_jsurfaceworks_src_JSurfaceWorks_FinalizedTmeshID
#define _Included_csw_jsurfaceworks_src_JSurfaceWorks_FinalizedTmeshID
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
