/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class csw_jsurfaceworks_src_JSurfaceWorksBase */

#ifndef _Included_csw_jsurfaceworks_src_JSurfaceWorksBase
#define _Included_csw_jsurfaceworks_src_JSurfaceWorksBase
#ifdef __cplusplus
extern "C" {
#endif
#undef csw_jsurfaceworks_src_JSurfaceWorksBase_SW_END_THREAD
#define csw_jsurfaceworks_src_JSurfaceWorksBase_SW_END_THREAD 6723L
#undef csw_jsurfaceworks_src_JSurfaceWorksBase_MAX_LIST_ARRAY
#define csw_jsurfaceworks_src_JSurfaceWorksBase_MAX_LIST_ARRAY 30L
#undef csw_jsurfaceworks_src_JSurfaceWorksBase_SMALL_CHUNK
#define csw_jsurfaceworks_src_JSurfaceWorksBase_SMALL_CHUNK 20L
#undef csw_jsurfaceworks_src_JSurfaceWorksBase_MEDIUM_CHUNK
#define csw_jsurfaceworks_src_JSurfaceWorksBase_MEDIUM_CHUNK 100L
#undef csw_jsurfaceworks_src_JSurfaceWorksBase_BIG_CHUNK
#define csw_jsurfaceworks_src_JSurfaceWorksBase_BIG_CHUNK 1000L
#undef csw_jsurfaceworks_src_JSurfaceWorksBase_HUGE_CHUNK
#define csw_jsurfaceworks_src_JSurfaceWorksBase_HUGE_CHUNK 10000L
/*
 * Class:     csw_jsurfaceworks_src_JSurfaceWorksBase
 * Method:    sendCommand
 * Signature: (II[I[J[DLjava/lang/String;[I[F[DI)J
 */
JNIEXPORT jlong JNICALL Java_csw_jsurfaceworks_src_JSurfaceWorksBase_sendCommand
  (JNIEnv *, jobject, jint, jint, jintArray, jlongArray, jdoubleArray, jstring, jintArray, jfloatArray, jdoubleArray, jint);

/*
 * Class:     csw_jsurfaceworks_src_JSurfaceWorksBase
 * Method:    sendStaticCommand
 * Signature: (II[I[J[DLjava/lang/String;[I[F[DI)J
 */
JNIEXPORT jlong JNICALL Java_csw_jsurfaceworks_src_JSurfaceWorksBase_sendStaticCommand
  (JNIEnv *, jclass, jint, jint, jintArray, jlongArray, jdoubleArray, jstring, jintArray, jfloatArray, jdoubleArray, jint);

/*
 * Class:     csw_jsurfaceworks_src_JSurfaceWorksBase
 * Method:    bootMe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_csw_jsurfaceworks_src_JSurfaceWorksBase_bootMe
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
