#!/bin/bash

./ezx_test utest.ezx;
./ezx_test utest.ezx;
./ezx_test utest.ezx;
./ezx_test utest.ezx;
./ezx_test utest.ezx;
./ezx_test utest.ezx;
./ezx_test utest.ezx;
./ezx_test utest.ezx;
./ezx_test utest.ezx;
./ezx_test utest.ezx;

./ezx_test utest.ezx;
./ezx_test utest.ezx;
./ezx_test utest.ezx;
./ezx_test utest.ezx;
./ezx_test utest.ezx;
./ezx_test utest.ezx;
./ezx_test utest.ezx;
./ezx_test utest.ezx;
./ezx_test utest.ezx;
./ezx_test utest.ezx;
