#!/bin/bash

export classpath=$CSW_PARENT
#lpath=/usr/java/jdk1.8.0_152/jre/lib/amd64
echo
cd $CSW_PARENT

#export EZ_PAINT_PRINT_TIMING=1
#export EZ_PRINT_TIMING=1
export SW_PRINT_TIMING=1
export PB_PRINT_TIMING=1

java -Xmx1500m -Djava.library.path=$CSW_PARENT/csw/lib  csw.jtest.$@
#java -Xmx500m -Djava.library.path=$CSW_PARENT/csw/lib  csw.jtest.$@

#unset EZ_PAINT_PRINT_TIMING
#unset EZ_PRINT_TIMING
unset SW_PRINT_TIMING
unset PB_PRINT_TIMING

cd csw/jtest

if [ -e "pbfile_0.txt" ]
then
  cat pb*.txt > utest.ezx
  rm -f pb*.txt
fi

if [ -e "swfile_0.txt" ]
then
  cat sw*.txt > utest.sw
  rm -f sw*.txt
fi

