.IGNORE:

include $(CSW_PARENT)/build/system.mk

JAVA_SRC=\
 DoubleField.java\
 FontName.java\
 IconCheckBox.java\
 IconToggleButton.java\
 JEasyXIcons.java\
 TextCheckBox.java\
 TextToggleButton.java\
 ValueChangeEvent.java\
 ValueChangeListener.java

JAVA_CLASSES=\
 DoubleField.class\
 FontName.class\
 IconCheckBox.class\
 IconToggleButton.class\
 JEasyXIcons.class\
 TextCheckBox.class\
 TextToggleButton.class\
 ValueChangeEvent.class\
 ValueChangeListener.class

all: java_classes

java_classes: $(JAVA_CLASSES)

PACKAGE_PATH=csw/uistuff
JAR_FILE=uistuff.jar

clean:
	$(RM) *.class *.jar
