.IGNORE:

include $(CSW_PARENT)/build/system.mk

JAVA_SRC=\
 Bounds2D.java\
 Bounds3D.java\
 ColorPalette.java\
 ContactPolyline.java\
 CSW_UI.java\
 FontChooser.java\
 LightData.java\
 MathUtils.java\
 NodeArray3D.java\
 TranslationManager.java\
 TriangleArray.java\
 View3DProperties.java\
 XYPoint.java\
 XYPolyline.java\
 XYZPoint.java\
 XYZPolyline.java\
 XYZNode.java\
 DoubleField.java

JAVA_CLASSES=\
 Bounds2D.class\
 Bounds3D.class\
 ColorPalette.class\
 ContactPolyline.class\
 CSW_UI.class\
 FontChooser.class\
 LightData.class\
 MathUtils.class\
 NodeArray3D.class\
 TranslationManager.class\
 TriangleArray.class\
 View3DProperties.class\
 XYPoint.class\
 XYPolyline.class\
 XYZPoint.class\
 XYZPolyline.class\
 XYZNode.class\
 DoubleField.class

PACKAGE_PATH=csw/jutils/src
JAR_FILE=jutils.jar

all: java_classes

java_classes: $(JAVA_CLASSES)

clean:
	$(RM) *.class *.jar
